

-----------------------------------------------------------------------------------------------------------------------------------------
select*from customer;

-- MODULE 1: DATABASE EXPLORATION
--Q1 How many purchase transactions are available for analysis?
SELECT COUNT(*) AS total_transactions
FROM customer;
--3900

--Q2 How many unique customers are represented in the dataset?
SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM customer;
--3900

--Q3 Which product categories are available in the retail business?
select distinct category from customer
order by category;

--Q4 What payment methods do customers use?
SELECT DISTINCT payment_method
FROM customer
ORDER BY payment_method;

--Q5 What shipping options are available to customers?
select distinct shipping_type from customer;


--MODULE 2: EXECUTIVE KPI ANALYTICS
--Q5 What is the total revenue generated by the retail company?
SELECT
    SUM(purchase_amount) AS total_revenue
	from customer;

--Q6 What is the average amount spent per purchase?
 SELECT
    ROUND(AVG(purchase_amount),2) AS average_purchase_amount
FROM customer;

--Q7 How satisfied are customers with their purchases?
SELECT
    ROUND(AVG(review_rating)::numeric, 2) AS average_review_rating
FROM customer;


--Q8 What percentage of customers are enrolled in the retailer's subscription program?
SELECT
    ROUND(
        100.0 *
        SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
    2) AS subscriber_percentage
FROM customer;

--Q9 How many purchases were made using discounts?
SELECT
    ROUND(
        100.0 *
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
    2) AS discount_utilization_rate
FROM customer;


SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'customer'
ORDER BY ordinal_position;



-- ============================================================
-- MODULE 3: CUSTOMER ANALYTICS
-- ============================================================

-- Q10. Do subscribers spend more than non-subscribers?

SELECT
    subscription_status,
    COUNT(*) AS total_customers,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount)::numeric,2) AS avg_purchase
FROM customer
GROUP BY subscription_status
ORDER BY avg_purchase DESC;


-- Q11. Which age group contributes the highest revenue?

SELECT
    age_group,
    COUNT(*) AS total_customers,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount)::numeric,2) AS avg_purchase
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


-- Q12. Which gender contributes more to total revenue?

SELECT
    gender,
    COUNT(*) AS total_customers,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount)::numeric,2) AS avg_purchase
FROM customer
GROUP BY gender;


-- Q13. Who are the top 10 highest spending customers?                ye ek smjhna hai 

SELECT
    customer_id,
    purchase_amount,
    RANK() OVER(ORDER BY purchase_amount DESC) AS customer_rank
FROM customer
LIMIT 10;


-- Q14. Which locations generate the highest revenue?

SELECT
    location,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY location
ORDER BY total_revenue DESC;


-- Q15. Does previous purchase history influence customer spending?

SELECT
    previous_purchases,
    COUNT(*) AS customers,
    ROUND(AVG(purchase_amount)::numeric,2) AS avg_purchase
FROM customer
GROUP BY previous_purchases
ORDER BY previous_purchases;


-- Q16. How does purchase frequency affect average customer spending?

SELECT
    frequency_of_purchases,
    COUNT(*) AS customers,
    ROUND(AVG(purchase_amount)::numeric,2) AS avg_purchase
FROM customer
GROUP BY frequency_of_purchases
ORDER BY avg_purchase DESC;


-- ============================================================
-- MODULE 4: PRODUCT ANALYTICS
-- ============================================================

-- Q17. Which product categories generate the highest revenue?

SELECT
    category,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY category
ORDER BY total_revenue DESC;


-- Q18. What are the top 10 highest revenue-generating products?

SELECT
    item_purchased,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY item_purchased
ORDER BY total_revenue DESC
LIMIT 10;


-- Q19. Which product colors are purchased most frequently?

SELECT
    color,
    COUNT(*) AS purchases
FROM customer
GROUP BY color
ORDER BY purchases DESC;


-- Q20. Which product sizes are most popular among customers?

SELECT
    size,
    COUNT(*) AS purchases
FROM customer
GROUP BY size
ORDER BY purchases DESC;


-- Q21. Which season generates the highest revenue?

SELECT
    season,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;


-- ============================================================
-- MODULE 5: CUSTOMER EXPERIENCE ANALYTICS
-- ============================================================

-- Q22. Which product categories receive the highest customer ratings?

SELECT
    category,
    ROUND(AVG(review_rating)::numeric,2) AS avg_rating
FROM customer
GROUP BY category
ORDER BY avg_rating DESC;


-- Q23. Which shipping method provides the highest customer satisfaction?

SELECT
    shipping_type,
    ROUND(AVG(review_rating)::numeric,2) AS avg_rating
FROM customer
GROUP BY shipping_type
ORDER BY avg_rating DESC;


-- Q24. Which payment method is preferred by customers?

SELECT
    payment_method,
    COUNT(*) AS total_transactions
FROM customer
GROUP BY payment_method
ORDER BY total_transactions DESC;


-- ============================================================
-- MODULE 6: ADVANCED SQL ANALYTICS
-- ============================================================

-- Q25. Rank product categories based on total revenue.

SELECT
    category,
    SUM(purchase_amount) AS revenue,
    RANK() OVER(ORDER BY SUM(purchase_amount) DESC) AS revenue_rank
FROM customer
GROUP BY category;


-- Q26. Identify the highest spending customer in each location.

SELECT *
FROM (
    SELECT
        customer_id,
        location,
        purchase_amount,
        ROW_NUMBER() OVER(PARTITION BY location ORDER BY purchase_amount DESC) AS rn
    FROM customer
) t
WHERE rn = 1;


-- Q27. Segment customers based on purchase amount and purchase history.

SELECT
    customer_id,
    purchase_amount,
    previous_purchases,
    CASE
        WHEN purchase_amount >= 80 AND previous_purchases >= 30 THEN 'Premium'
        WHEN purchase_amount >= 60 THEN 'High Value'
        WHEN purchase_amount >= 40 THEN 'Regular'
        ELSE 'Low Value'
    END AS customer_segment
FROM customer;


-- Q28. What percentage of total revenue does each product category contribute?             crazy

SELECT
    category,
    SUM(purchase_amount) AS revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 /
        SUM(SUM(purchase_amount)) OVER(),
        2
    ) AS revenue_percentage
FROM customer
GROUP BY category
ORDER BY revenue DESC;


-- Q29. Calculate the cumulative revenue contribution by product category.

SELECT
    category,
    SUM(purchase_amount) AS revenue,
    SUM(SUM(purchase_amount))
    OVER(ORDER BY SUM(purchase_amount) DESC) AS cumulative_revenue
FROM customer
GROUP BY category;


-- Q30. Create a customer summary view for reporting and dashboarding.
SELECT * FROM customer_summary;

CREATE VIEW customer_summary AS
SELECT
    customer_id,
    age_group,
    gender,
    location,
    purchase_amount,
    previous_purchases,
    category,
    review_rating,
    CASE
        WHEN purchase_amount >= 80 AND previous_purchases >= 30 THEN 'Premium'
        WHEN purchase_amount >= 60 THEN 'High Value'
        WHEN purchase_amount >= 40 THEN 'Regular'
        ELSE 'Low Value'
    END AS customer_segment
FROM customer;


select Location,
sum(purchase_amount)
from customer
group by Location
order by sum(purchase_amount) desc
select*from customer
